.TH STACKTILE 1 2021-07-17 "git.sr.ht/~leon_plickat/stacktile" "General Commands Manual"
.
.SH NAME
.P
stacktile \- a layout generator for the river Wayland compositor
.
.
.SH DESCRIPTION
.P
stacktile is a layout generator for river.
.P
It devides the screen into three areas, the primary area, the secondary area and
the remainder area.
The primary and secondary areas are populated by a configurable amount of
windows from the top of the window stack.
All remaining windows will be placed in the remainder area.
The windows in these areas are arranged into a configurable sublayout.
.P
stacktile is highly adaptable and should fit many use cases.
By default, stacktile uses the same layout values for all tag sets of an output,
but per tag values can be enabled as well.
.
.
.SH OPTIONS
.P
\fB--per-tag-config\fR
.RS
If this option is set, individual tag sets will have individual layout
values.
If any value of the layout is changed, the change will only apply to the
currently focused tag set, instead of to all tag sets on the output.
.RE
.
.P
\fB--primary-count\fR \fIvalue\fR
.RS
Set the default amount of windows in the primary area.
\fIvalue\fR must be a non-negative integer.
.RE
.
.P
\fB--primary-ratio\fR \fIvalue\fR
.RS
Set the default relative width of the primary area.
\fIvalue\fR must be a floating point number between 0.1 and 0.9.
.RE
.
.P
\fB--primary-sublayout\fR \fBcolumns\fR|\fBrows\fR|\fBstack\fR|\fBgrid\fR
.RS
Set the default sublayout of the primary area.
.RE
.
.P
\fB--primary-position\fR \fBtop\fR|\fBright\fR|\fBbottom\fR|\fBleft\fR
.RS
Set the default position of the primary area.
.RE
.
.P
\fB--secondary-count\fR \fIvalue\fR
.RS
Set the default amount of windows in the secondary area.
\fIvalue\fR must be a non-negative integer.
.RE
.
.P
\fB--secondary-ratio\fR \fIvalue\fR
.RS
Set the default relative height of the secondary area.
\fIvalue\fR must be a floating point number between 0.1 and 0.9.
.RE
.
.P
\fB--secondary-sublayout\fR \fBcolumns\fR|\fBrows\fR|\fBstack\fR|\fBgrid\fR
.RS
Set the default sublayout of the secondary area.
.RE
.
.P
\fB--remainder-sublayout\fR \fBcolumns\fR|\fBrows\fR|\fBstack\fR|\fBgrid\fR
.RS
Set the default sublayout of the remainder area.
.RE
.
.P
\fB --inner-padding\fR \fIvalue\fR
.RS
Set the default padding between windows.
\fIvalue\fR must be a non-negative integer.
.RE
.
.P
\fB--outer-padding\fR \fIvalue\fR
.RS
Set the default padding around the layout.
\fIvalue\fR must be a non-negative integer.
.RE
.
.
.SH COMMANDS
.P
These commands may be send to stacktile at runtime with the help of
\fBriverctl\fR(1).
.
.P
\fBprimary_count\fR \fIvalue\fR
.RS
Set or modify the amount of windows in the primary area.
\fIvalue\fR must be an integer.
If \fIvalue\fR is prefixed by a + or \- sign, it is added or subtracted from the
current primary count.
Otherwise primary count will be set to \fIvalue\fR.
The primary count may not be negative.
.RE
.
.P
\fBprimary_ratio\fR \fIvalue\fR
.RS
Set or modify the relative width of the primary area.
\fIvalue\fR must be a floating point number.
If \fIvalue\fR is prefixed by a + or \- sign, it is added or subtracted from the
current primary ratio.
Otherwise primary ratio will be set to \fIvalue\fR.
The primary ration is clamped to the range of 0.1\(en0.9.
.RE
.
.P
\fBprimary_sublayout\fR \fBcolumns\fR|\fBrows\fR|\fBstack\fR|\fBgrid\fR
.RS
Set the sublayout of the primary area.
.RE
.
.P
\fBprimary_position\fR \fBtop\fR|\fBright\fR|\fBbottom\fR|\fBleft\fR
.RS
Set the position of the primary area.
.RE
.
.P
\fBsecondary_count\fR \fIvalue\fR
.RS
Set or modify the amount of windows in the secondary area.
\fIvalue\fR must be an integer.
If \fIvalue\fR is prefixed by a + or \- sign, it is added or subtracted from the
current secondary count.
Otherwise secondary count will be set to \fIvalue\fR.
The secondary count may not be negative.
.RE
.
.P
\fBsecondary_ratio\fR \fIvalue\fR
.RS
Set or modify the relative height of the secondary area.
\fIvalue\fR must be a floating point number.
If \fIvalue\fR is prefixed by a + or \- sign, it is added or subtracted from the
current secondary ratio.
Otherwise secondary ratio will be set to \fIvalue\fR.
The secondary ration is clamped to the range of 0.1\(en0.9.
.RE
.
.P
\fBsecondary_sublayout\fR \fBcolumns\fR|\fBrows\fR|\fBstack\fR|\fBgrid\fR
.RS
Set the sublayout of the secondary area.
.RE
.
.P
\fBremainder_sublayout\fR \fBcolumns\fR|\fBrows\fR|\fBstack\fR|\fBgrid\fR
.RS
Set the sublayout of the remainder area.
.RE
.
.P
\fBinner_padding\fR \fIvalue\fR
.RS
Set or modify the padding between windows.
\fIvalue\fR must be an integer.
If \fIvalue\fR is prefixed by a + or \- sign, it is added or subtracted from the
current inner padding.
Otherwise inner padding will be set to \fIvalue\fR.
The inner padding may not be negative.
.RE
.
.P
\fBouter_padding\fR \fIvalue\fR
.RS
Set or modify around the layout.
\fIvalue\fR must be an integer.
If \fIvalue\fR is prefixed by a + or \- sign, it is added or subtracted from the
current outer padding.
Otherwise outer padding will be set to \fIvalue\fR.
The outer padding may not be negative.
.RE
.
.P
\fBall_padding\fR \fIvalue\fR
.RS
Set or modify both the inner and outer padding.
\fIvalue\fR must be an integer.
If \fIvalue\fR is prefixed by a + or \- sign, it is added or subtracted from the
current inner and outer padding.
Otherwise the inner and outer padding will be set to \fIvalue\fR.
Padding may not be negative.
.RE
.
.P
\fBall_primary\fR \fBtrue\fR|\fBfalse\fR|\fBtoggle\fR
.RS
If this option is active, all windows will be placed in the primary area.
.RE
.
.P
\fBreset\fR
.RS
Delete the modified layout variables for all tag sets, returning to the defaults.
.RE
.
.
.SH AUTHOR
.P
.MT leonhenrik.plickat@stud.uni-goettingen.de
Leon Henrik Plickat
.ME
.
.
.SH SEE ALSO
.BR river (1)
.BR riverctl (1)
